version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "aws-lambda-to-gcp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "gcp-functions-to-aws"
    schedule:
      interval: "weekly"
